#!/usr/bin/env python3
"""
NEW: Agentic Fargate Agent
AI runs INSIDE Fargate with full codebase access
Makes fixes iteratively until build passes
"""

import os
import sys
import json
import boto3
import subprocess
import logging
from datetime import datetime
from agentcore_fixer import AgentCoreFixer
from agentic_fixer import AgenticFixer

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

# AWS clients
dynamodb = boto3.resource('dynamodb')
secrets_manager = boto3.client('secretsmanager')
bedrock = boto3.client('bedrock-runtime', region_name='us-east-1')

# Environment variables
PROJECT_ID = os.environ.get('PROJECT_ID')
DYNAMODB_TABLE = os.environ.get('DYNAMODB_TABLE', 'accessagent-projects')


def get_github_token():
    """Get GitHub token from Secrets Manager"""
    try:
        response = secrets_manager.get_secret_value(SecretId='accessagent/github-token')
        secret = json.loads(response['SecretString'])
        return secret['token']
    except Exception as e:
        logger.error(f"Failed to get GitHub token: {e}")
        raise


def update_progress(status, message, progress=None):
    """Update project progress in DynamoDB"""
    try:
        table = dynamodb.Table(DYNAMODB_TABLE)
        update_expr = "SET #status = :status, updated_at = :timestamp"
        expr_names = {"#status": "status"}
        expr_values = {
            ":status": status,
            ":timestamp": datetime.utcnow().isoformat()
        }
        
        if progress is not None:
            update_expr += ", progress = :progress"
            expr_values[":progress"] = str(progress)
        
        # Add activity log
        log_entry = {
            "timestamp": datetime.utcnow().isoformat(),
            "message": message,
            "step": status
        }
        update_expr += ", activity_log = list_append(if_not_exists(activity_log, :empty_list), :log)"
        expr_values[":log"] = [log_entry]
        expr_values[":empty_list"] = []
        
        table.update_item(
            Key={"project_id": PROJECT_ID},
            UpdateExpression=update_expr,
            ExpressionAttributeNames=expr_names,
            ExpressionAttributeValues=expr_values
        )
        logger.info(f"Progress: {status} - {message}")
    except Exception as e:
        logger.error(f"Failed to update progress: {e}")


def get_project_data():
    """Get project data from DynamoDB"""
    try:
        table = dynamodb.Table(DYNAMODB_TABLE)
        response = table.get_item(Key={"project_id": PROJECT_ID})
        if 'Item' not in response:
            raise Exception(f"Project {PROJECT_ID} not found")
        return response['Item']
    except Exception as e:
        logger.error(f"Failed to get project data: {e}")
        raise


def clone_repo(repo_url, github_token):
    """Clone repository"""
    logger.info(f"Cloning {repo_url}")
    
    # Extract owner/repo from URL
    parts = repo_url.replace("https://github.com/", "").split("/")
    owner, repo = parts[0], parts[1]
    
    # Clone with token authentication
    auth_url = f"https://{github_token}@github.com/{owner}/{repo}.git"
    repo_dir = f"/workspace/{repo}"
    
    try:
        subprocess.run(
            ["git", "clone", auth_url, repo_dir],
            check=True,
            capture_output=True,
            text=True
        )
        logger.info(f"✓ Cloned to {repo_dir}")
        return repo_dir, owner, repo
    except subprocess.CalledProcessError as e:
        logger.error(f"Clone failed: {e.stderr}")
        raise


def push_and_create_pr(repo_dir, owner, repo, github_token, branch_name, modified_files, summary):
    """Push changes and create PR"""
    logger.info(f"Creating branch {branch_name}")
    
    try:
        # Configure git with user's real credentials (for Vercel verification)
        subprocess.run(["git", "config", "user.name", "Geeth Gunnampalli"], cwd=repo_dir, check=True)
        subprocess.run(["git", "config", "user.email", "geeth.gunnampalli@gmail.com"], cwd=repo_dir, check=True)
        
        # Create branch
        subprocess.run(["git", "checkout", "-b", branch_name], cwd=repo_dir, check=True)
        
        # Add and commit
        subprocess.run(["git", "add", "."], cwd=repo_dir, check=True)
        commit_message = f"fix(a11y): Improve accessibility\n\n{summary}\n\n✨ Generated by AccessAgent AI Agent\n📝 Modified {len(modified_files)} files"
        subprocess.run(["git", "commit", "-m", commit_message], cwd=repo_dir, check=True)
        
        # Push
        push_url = f"https://{github_token}@github.com/{owner}/{repo}.git"
        subprocess.run(["git", "push", push_url, branch_name], cwd=repo_dir, check=True)
        
        # Create PR using GitHub API
        import requests
        pr_data = {
            "title": "🎯 Automated Accessibility Improvements",
            "body": f"{summary}\n\n**Files Modified:**\n" + "\n".join([f"- `{f}`" for f in modified_files]),
            "head": branch_name,
            "base": "main"
        }
        
        response = requests.post(
            f"https://api.github.com/repos/{owner}/{repo}/pulls",
            headers={
                "Authorization": f"Bearer {github_token}",
                "Accept": "application/vnd.github.v3+json"
            },
            json=pr_data
        )
        
        if response.status_code == 201:
            pr_url = response.json()['html_url']
            logger.info(f"✓ Created PR: {pr_url}")
            return pr_url
        else:
            logger.error(f"Failed to create PR: {response.text}")
            return None
            
    except Exception as e:
        logger.error(f"Failed to push/create PR: {e}")
        raise


def main():
    """
    NEW Main Workflow:
    1. Clone repo
    2. Initialize AgenticFixer with full codebase access
    3. AI makes fixes iteratively
    4. AI builds and fixes build errors
    5. Repeats until build passes
    6. Push PR
    """
    logger.info(f"🤖 Starting AGENTIC Fargate Agent for project {PROJECT_ID}")
    
    try:
        # Get project data
        update_progress("processing", "Agentic agent started", 50)
        project = get_project_data()
        
        repo_url = project['repo_url']
        
        # Parse agent_results to get issues
        agent_results = json.loads(project.get('agent_results', '{}'))
        issues = []
        for step in agent_results.get('steps', []):
            if step['step'] == 'scan':
                scan_body = json.loads(step['result']['body'])
                issues = scan_body.get('issues', [])
                break
        
        logger.info(f"Got {len(issues)} accessibility issues to fix")
        
        # Get GitHub token
        github_token = get_github_token()
        
        # Clone repository
        update_progress("processing", "Cloning repository with full code access...", 55)
        repo_dir, owner, repo = clone_repo(repo_url, github_token)
        
        # 🚀 NEW: Initialize AgentCore Fixer (using Bedrock AgentCore primitives)
        update_progress("processing", "AgentCore analyzing codebase with code interpreter...", 60)
        fixer = AgentCoreFixer(
            repo_path=repo_dir,
            issues=issues,
            bedrock_client=bedrock
        )
        
        # Run the AgentCore fix loop
        update_progress("processing", "AgentCore making fixes with code interpreter primitive...", 70)
        result = fixer.run_fix_loop()
        
        if not result['success']:
            error_msg = result.get('error', 'Build failed after all iterations')
            update_progress("error", f"Agent error: {error_msg}")
            raise Exception(error_msg)
        
        logger.info(f"✅ Build passed after {result['iterations']} iterations!")
        
        # Get list of modified files
        git_status = subprocess.run(
            ["git", "diff", "--name-only"],
            cwd=repo_dir,
            capture_output=True,
            text=True
        ).stdout.strip().split('\n')
        
        modified_files = [f for f in git_status if f]
        logger.info(f"Modified files: {modified_files}")
        
        # Push and create PR
        update_progress("processing", "Creating pull request...", 90)
        branch_name = f"accessagent/{PROJECT_ID[:8]}"
        summary = f"Fixed {len(issues)} accessibility issues through {result['iterations']} AI-powered iterations"
        
        pr_url = push_and_create_pr(repo_dir, owner, repo, github_token, branch_name, modified_files, summary)
        
        if pr_url:
            # Update DynamoDB with PR info
            table = dynamodb.Table(DYNAMODB_TABLE)
            table.update_item(
                Key={"project_id": PROJECT_ID},
                UpdateExpression="SET pr_url = :pr_url, pr_number = :pr_num, branch_name = :branch, #status = :status, progress = :progress",
                ExpressionAttributeNames={"#status": "status"},
                ExpressionAttributeValues={
                    ":pr_url": pr_url,
                    ":pr_num": pr_url.split('/')[-1],
                    ":branch": branch_name,
                    ":status": "completed",
                    ":progress": "100"
                }
            )
            
            update_progress("completed", f"✅ PR created: {pr_url}", 100)
            logger.info(f"🎉 Agent completed successfully!")
        else:
            raise Exception("Failed to create PR")
        
    except Exception as e:
        logger.error(f"Agent failed: {e}", exc_info=True)
        update_progress("error", f"Agent error: {str(e)}")
        sys.exit(1)


if __name__ == "__main__":
    main()

